import { z } from 'zod';

/**
 * GROWTH contract: how somebody arrives, and how VELORA counts it.
 *
 * The domain exists because every other way of getting people here costs money
 * VELORA does not have. What is left is a person telling another person, a
 * public page a search engine can read, and a time everybody agrees to be here
 * at — and each of those needs exactly one durable fact recorded about it or it
 * cannot be told apart from a guess.
 *
 * Three rules shape everything below.
 *
 * **An invitation is not a credential.** The code opens a page and attributes a
 * signup, and it authorises nothing else: it cannot admit anybody to a club,
 * grant an entitlement, or stand in for a session. Anything a holder of a code
 * can do, a stranger typing the same address can do, which is why it is safe to
 * post one publicly.
 *
 * **Attribution happens once, at the moment an account is created, and never
 * again.** Not on the first click, not on the tenth, and not when an existing
 * account opens somebody's link. That is a property of when the write happens
 * rather than a rule a service remembers to apply.
 *
 * **No number here is a claim about people.** A scheduled window carries a
 * start, an end, and a name, and carries no attendee count, no "42 people
 * going", and no estimate — because nothing knows, and a number nobody can
 * verify is the same lie whether it flatters the platform or not.
 */

/**
 * The code in an invitation address.
 *
 * Twenty-two characters from a thirty-six character alphabet, which is about
 * 113 bits. That is not a security boundary — the code authorises nothing — but
 * it is what makes the space unguessable, and an unguessable code is what stops
 * somebody harvesting invitations by counting upwards. It is lowercase and
 * alphanumeric so it survives being read aloud, retyped, and lowercased by a
 * chat client that thinks it is being helpful.
 *
 * It is deliberately not derived from anything. A code built from a user
 * identifier would publish that identifier to everybody who was ever sent a
 * link.
 */
export const inviteCodeSchema = z
  .string()
  .regex(/^[a-z0-9]{22}$/u, 'Invite code must be 22 lowercase alphanumerics');

/**
 * One visitor's own key for one invitation opening.
 *
 * Generated by the surface, kept for that browser, and sent when an invitation
 * page is opened. It exists so refreshing a page ten times is one opening
 * rather than ten, and it identifies nothing: it is not stored against an
 * account, never leaves this one purpose, and is worth nothing to anybody who
 * holds it. Bounded and shaped so it cannot carry anything else.
 */
export const invitationOpeningKeySchema = z
  .string()
  .regex(/^[a-z0-9]{22}$/u, 'Opening key must be 22 lowercase alphanumerics');

/**
 * One campaign field, as it arrives from an address bar.
 *
 * Accepted generously and trusted for nothing. The value is somebody else's
 * string — it came out of a link anybody can write — so it is bounded here and
 * normalised by the server before storage: it names where a signup came from
 * and is never read as permission, as money, or as an identity.
 *
 * The bound is larger than anything worth storing on purpose so an ordinary
 * over-long campaign name is truncated rather than refusing somebody's signup.
 */
export const acquisitionParameterSchema = z.string().min(1).max(200);

/** The longest a normalised campaign field is kept. */
export const maximumAcquisitionParameterCharacters = 64;

/**
 * Where an account came from, as far as anything can honestly say.
 *
 * Sent once, with the request that creates the account, and never accepted
 * again. Every field is optional because most signups have none of them, and
 * the object as a whole is optional because a person typing the address in is
 * the most honest arrival there is.
 */
export const acquisitionSchema = z
  .object({
    campaign: acquisitionParameterSchema.optional(),
    content: acquisitionParameterSchema.optional(),
    /** The invitation this person arrived through, if they arrived through one. */
    inviteCode: inviteCodeSchema.optional(),
    medium: acquisitionParameterSchema.optional(),
    source: acquisitionParameterSchema.optional(),
  })
  .strict();
export type Acquisition = z.infer<typeof acquisitionSchema>;

/**
 * The invitation link one person holds.
 *
 * One per account, forever, rather than one per share. A person who has sent
 * their link to six people and then generates a seventh code has broken the six
 * links they already sent, and nothing about this product needs per-share
 * accounting badly enough to pay for that.
 */
export const inviteLinkSchema = z
  .object({
    code: inviteCodeSchema,
    createdAt: z.iso.datetime(),
  })
  .strict();
export type InviteLink = z.infer<typeof inviteLinkSchema>;

/** The caller's own link, or nothing if they have never made one. */
export const inviteLinkResponseSchema = z
  .object({ invite: inviteLinkSchema.optional() })
  .strict();
export type InviteLinkResponse = z.infer<typeof inviteLinkResponseSchema>;

export const invitationOpeningRequestSchema = z
  .object({
    code: inviteCodeSchema,
    openingKey: invitationOpeningKeySchema,
  })
  .strict();
export type InvitationOpeningRequest = z.infer<
  typeof invitationOpeningRequestSchema
>;

/**
 * Whether this code will attribute a signup, and nothing else.
 *
 * It deliberately does not say who invited you. An invitation address can be
 * forwarded, posted, or scraped, so anything this answered would be answered to
 * everybody who ever saw the link — and "somebody named X invited you" is a
 * fact about X that X did not agree to publish to strangers. The page it feeds
 * says a person invited you and gets on with explaining VELORA.
 */
export const invitationOpeningResponseSchema = z
  .object({ usable: z.boolean() })
  .strict();
export type InvitationOpeningResponse = z.infer<
  typeof invitationOpeningResponseSchema
>;

/**
 * Where a scheduled window is, relative to now.
 *
 * Derived from the two instants on every read rather than stored, because a
 * stored state is a state that is wrong between the moment it should change and
 * the moment something changes it — and the thing that would change it is a job
 * that can be late, restarted, or not running at all.
 */
export const liveWindowStateSchema = z.enum(['upcoming', 'active', 'ended']);
export type LiveWindowState = z.infer<typeof liveWindowStateSchema>;

export const liveWindowSlugSchema = z
  .string()
  .regex(
    /^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$/u,
    'Live window slug must be lowercase alphanumerics and hyphens',
  );

export const liveWindowTitleSchema = z.string().min(2).max(80);

/**
 * A time everybody is asked to be here at.
 *
 * The whole mechanism, and it is deliberately thin. It has no host, no
 * attendee list, no capacity, and no registration: it is an announcement that
 * more people than usual intend to be looking during these two hours, and the
 * thing it points at is ordinary Live, which works exactly as it always does
 * before, during, and after.
 *
 * Both instants are UTC and are rendered in the reader's own zone by whatever
 * is showing them. Storing a zone here would be storing the operator's zone,
 * which is nobody's.
 */
export const liveWindowSchema = z
  .object({
    endsAt: z.iso.datetime(),
    slug: liveWindowSlugSchema,
    startsAt: z.iso.datetime(),
    state: liveWindowStateSchema,
    title: liveWindowTitleSchema,
  })
  .strict();
export type LiveWindow = z.infer<typeof liveWindowSchema>;

/** How many windows one answer carries. Small: this is an announcement, not a calendar. */
export const maximumLiveWindows = 5;

export const liveWindowListResponseSchema = z
  .object({ windows: z.array(liveWindowSchema).max(maximumLiveWindows) })
  .strict();
export type LiveWindowList = z.infer<typeof liveWindowListResponseSchema>;

export const scheduleLiveWindowRequestSchema = z
  .object({
    endsAt: z.iso.datetime(),
    slug: liveWindowSlugSchema,
    startsAt: z.iso.datetime(),
    title: liveWindowTitleSchema,
  })
  .strict();
export type ScheduleLiveWindowRequest = z.infer<
  typeof scheduleLiveWindowRequestSchema
>;

export const liveWindowCancellationRequestSchema = z
  .object({ slug: liveWindowSlugSchema })
  .strict();
export type LiveWindowCancellationRequest = z.infer<
  typeof liveWindowCancellationRequestSchema
>;

/**
 * What an operator can be told about acquisition, and the shape of the limit.
 *
 * Counts of things GROWTH itself owns, over a window, and nothing joined to
 * anybody's account. There is no per-inviter leaderboard, no list of who
 * invited whom, and no conversion percentage: the first two would publish one
 * person's social graph to an operator who has no decision to make about it,
 * and the third would be a number this domain cannot compute honestly, because
 * whether somebody went on to use the product is USERS' and LIVE's fact rather
 * than GROWTH's.
 */
export const acquisitionSourceCountSchema = z
  .object({
    signups: z.number().int().nonnegative(),
    /** `invite` for an invitation, otherwise the normalised campaign source. */
    source: z.string().min(1).max(maximumAcquisitionParameterCharacters),
  })
  .strict();

export const acquisitionSummaryResponseSchema = z
  .object({
    invitationsOpened: z.number().int().nonnegative(),
    invitesCreated: z.number().int().nonnegative(),
    signupsAttributed: z.number().int().nonnegative(),
    /** The instant the counts start from, so nobody has to guess the window. */
    since: z.iso.datetime(),
    sources: z.array(acquisitionSourceCountSchema).max(50),
  })
  .strict();
export type AcquisitionSummary = z.infer<
  typeof acquisitionSummaryResponseSchema
>;
