import type { Money } from '../money/money.js';
import type { RecipientStatus } from './policy.js';

/**
 * The payout provider port.
 *
 * Every payout interaction Velora will ever need, named once, in Velora's
 * vocabulary. The interface is declared in full rather than grown method by
 * method because it is a specification of what an eligible payout provider must
 * be able to do — and that is the thing a provider is assessed against.
 *
 * [Provider eligibility](../../../../docs/compliance/06-payment-provider-eligibility.md)
 * records, from primary sources, that no assessed payout provider is eligible:
 * Stripe Connect and PayPal Payouts inherit their platforms' prohibitions,
 * Wise prohibits both the content category and third-party money transmission
 * outright, and Airwallex lists adult content as unsupported. The port exists
 * so that the accounting and orchestration around a payout are built and
 * exercised while that stays true.
 *
 * Two rules bind every implementation, and one shapes the whole interface.
 *
 * Nothing here is called inside a database transaction, and nothing here
 * returns authority — a provider answer is evidence PAYOUTS evaluates.
 *
 * And onboarding is the provider's, not Velora's. `startOnboarding` returns a
 * link to the provider's own hosted flow; there is no method that accepts a
 * bank account number, a routing number, a government identifier, or an
 * identity document, because there is nowhere in Velora for one to go. That is
 * a stronger statement than validating such a field away: the field does not
 * exist.
 */

export interface PayoutRecipientSnapshot {
  /** The provider's identifier for its own record of this creator. */
  readonly providerReference: string;
  /** What the provider says it can do for this recipient, normalized. */
  readonly status: RecipientStatus;
}

export interface PayoutOnboardingSession {
  /**
   * The provider-hosted page the creator completes onboarding on.
   *
   * Velora never renders a bank field or an identity-document upload. The
   * collection, the verification, and the retention of that material are the
   * provider's, under the provider's own compliance obligations.
   */
  readonly onboardingUrl: string;
  readonly providerReference: string;
}

export const payoutStatuses = ['submitted', 'paid', 'failed'] as const;
export type PayoutStatus = (typeof payoutStatuses)[number];

export interface PayoutInstructionRequest {
  readonly amount: Money;
  /**
   * Velora's key for this instruction.
   *
   * Generated by the platform and stable across retries of the same
   * instruction, so a provider that already paid returns the same object rather
   * than paying a second time. This is what stops a retry after a network
   * timeout from disbursing twice.
   */
  readonly idempotencyKey: string;
  /** The PAYOUTS instruction this belongs to. */
  readonly operationReference: string;
  readonly recipientReference: string;
}

export interface PayoutSnapshot {
  readonly amount: Money;
  readonly providerReference: string;
  readonly status: PayoutStatus;
}

export interface PayoutProviderPort {
  /** Adapter name, recorded on every instruction for audit and routing. */
  readonly provider: string;
  /** Authoritative current state, for reconciliation and ambiguous outcomes. */
  retrievePayout(providerReference: string): Promise<PayoutSnapshot>;
  /** Where the provider says this recipient currently stands. */
  retrieveRecipient(
    providerReference: string,
  ): Promise<PayoutRecipientSnapshot>;
  sendPayout(request: PayoutInstructionRequest): Promise<PayoutSnapshot>;
  /** Opens the provider's own hosted onboarding for one creator. */
  startOnboarding(input: {
    readonly creatorReference: string;
    readonly returnUrl: string;
  }): Promise<PayoutOnboardingSession>;
}

/**
 * The payout provider Velora is configured with in every deployed environment.
 *
 * It refuses rather than returning a pending state, for the same reason the
 * payment adapter does: a payout instruction nobody can settle would be a
 * durable record of an intention to send somebody money through a provider that
 * does not exist.
 */
export class UnavailablePayoutProvider implements PayoutProviderPort {
  readonly provider = 'unavailable';

  retrievePayout(): Promise<PayoutSnapshot> {
    return Promise.reject(this.refusal());
  }

  retrieveRecipient(): Promise<PayoutRecipientSnapshot> {
    return Promise.reject(this.refusal());
  }

  sendPayout(): Promise<PayoutSnapshot> {
    return Promise.reject(this.refusal());
  }

  startOnboarding(): Promise<PayoutOnboardingSession> {
    return Promise.reject(this.refusal());
  }

  private refusal(): Error {
    return new Error('No approved payout provider is configured');
  }
}
