import type { Money } from '../money/money.js';
import type { BillingInterval } from './offer-policy.js';

/**
 * The payment provider port.
 *
 * Every provider interaction Velora will ever need, named once, in Velora's
 * vocabulary. No provider object shape, status string, error code, or SDK type
 * crosses this boundary: a domain that spoke a vendor's language would have to
 * be rewritten when the vendor changed, and
 * [provider eligibility](../../../../docs/compliance/06-payment-provider-eligibility.md)
 * makes a provider change likely rather than hypothetical — several providers
 * that permit Velora today prohibit it outright the moment mature creator
 * content is considered.
 *
 * The interface is declared in full here rather than grown method by method,
 * because it is a specification of what an eligible provider must be able to
 * do, and that is the thing a provider is assessed against. Callers arrive per
 * phase: checkout creation and retrieval now, verified event ingestion with the
 * webhook inbox, refunds with reversal accounting, and reconciliation with the
 * jobs that repair ambiguous state.
 *
 * Two rules bind every implementation. Nothing here is called inside a database
 * transaction — [ADR-0021](../../../../docs/decisions/ADR-0021-monetization-money-architecture.md)
 * requires the operation to be committed before the network call and recorded
 * after it. And nothing here returns authority: a provider answer is evidence
 * that BILLING evaluates, never a decision it adopts.
 */

/**
 * What a provider says about a payment, in Velora's terms.
 *
 * Deliberately small, and deliberately not a mirror of any provider's status
 * vocabulary. A provider that publishes fifteen states maps them onto these
 * five inside its adapter, so a new state at a vendor is an adapter change
 * rather than a domain migration.
 *
 * There is no `unknown`. A provider that cannot say is an ambiguous outcome,
 * which is an absent answer rather than a state — the adapter throws and the
 * operation stays pending for reconciliation.
 */
export const providerPaymentStatuses = [
  'pending',
  'requires_action',
  'succeeded',
  'failed',
  'cancelled',
] as const;
export type ProviderPaymentStatus = (typeof providerPaymentStatuses)[number];

export const providerRefundStatuses = [
  'pending',
  'succeeded',
  'failed',
] as const;
export type ProviderRefundStatus = (typeof providerRefundStatuses)[number];

export interface ProviderCheckoutRequest {
  readonly amount: Money;
  /** Where the provider returns a consumer who abandoned the payment. */
  readonly cancelUrl: string;
  /**
   * An opaque platform reference for the paying consumer.
   *
   * Never a name, an email address, or anything else identifying. A provider
   * that needs contact details collects them itself, on its own page, under its
   * own compliance obligations.
   */
  readonly consumerReference: string;
  readonly correlationId: string;
  /** Present exactly when the mode recurs. */
  readonly interval?: BillingInterval;
  /**
   * Velora's idempotency key for this instruction.
   *
   * Generated by the platform and stable across retries of the same operation,
   * so a provider that already acted on it returns the same object rather than
   * creating a second one. This is what stops a retry after a network timeout
   * from charging somebody twice.
   */
  readonly idempotencyKey: string;
  readonly mode: 'payment' | 'subscription';
  /** The BILLING payment operation this instruction belongs to. */
  readonly operationReference: string;
  /** Where the provider returns a consumer who completed the payment. */
  readonly returnUrl: string;
}

export interface ProviderCheckoutSession {
  /** The provider's identifier for the object it created. */
  readonly providerReference: string;
  /**
   * The provider-hosted page the consumer completes payment on.
   *
   * Velora never renders a card field. Collection happens on the provider's
   * own page, under the provider's own PCI scope, and no primary account
   * number or security code ever reaches a Velora process.
   */
  readonly redirectUrl: string;
  readonly status: ProviderPaymentStatus;
}

export interface ProviderPaymentSnapshot {
  readonly amount: Money;
  readonly providerReference: string;
  readonly status: ProviderPaymentStatus;
}

export interface ProviderRefundRequest {
  readonly amount: Money;
  readonly idempotencyKey: string;
  readonly operationReference: string;
  readonly providerPaymentReference: string;
}

export interface ProviderRefundSnapshot {
  readonly amount: Money;
  readonly providerReference: string;
  readonly status: ProviderRefundStatus;
}

/**
 * A provider event, after its signature has been verified.
 *
 * The payload is deliberately minimized rather than passed through: a verified
 * event contributes an identity, a type, and the references BILLING needs to
 * find its own record. Everything else stays at the provider.
 */
export interface ProviderEventEnvelope {
  readonly eventId: string;
  readonly eventType: string;
  readonly occurredAt: Date;
  readonly providerPaymentReference?: string;
  readonly providerRefundReference?: string;
  readonly status?: ProviderPaymentStatus;
}

export interface PaymentProviderPort {
  /** Adapter name, recorded on every operation for audit and routing. */
  readonly provider: string;
  createCheckout(
    request: ProviderCheckoutRequest,
  ): Promise<ProviderCheckoutSession>;
  refundPayment(
    request: ProviderRefundRequest,
  ): Promise<ProviderRefundSnapshot>;
  /** Authoritative current state, for reconciliation and ambiguous outcomes. */
  retrievePayment(providerReference: string): Promise<ProviderPaymentSnapshot>;
  /**
   * Verifies an inbound webhook and normalizes it, or refuses.
   *
   * The raw body is passed verbatim because signature verification is computed
   * over exactly the bytes that arrived; parsing first and re-serializing would
   * verify a different document.
   */
  verifyEvent(input: {
    readonly headers: Headers;
    readonly rawBody: string;
  }): Promise<ProviderEventEnvelope>;
}

/**
 * The provider Velora is configured with in every deployed environment.
 *
 * It refuses rather than returning a pending state, because a pending payment
 * nobody can settle is worse than a refusal: it would be a durable record of an
 * intention to charge somebody through a provider that does not exist.
 */
export class UnavailablePaymentProvider implements PaymentProviderPort {
  readonly provider = 'unavailable';

  createCheckout(): Promise<ProviderCheckoutSession> {
    return Promise.reject(this.refusal());
  }

  refundPayment(): Promise<ProviderRefundSnapshot> {
    return Promise.reject(this.refusal());
  }

  retrievePayment(): Promise<ProviderPaymentSnapshot> {
    return Promise.reject(this.refusal());
  }

  verifyEvent(): Promise<ProviderEventEnvelope> {
    return Promise.reject(this.refusal());
  }

  private refusal(): Error {
    return new Error('No approved payment provider is configured');
  }
}
