import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  withAndroidManifest,
  withAppBuildGradle,
  withDangerousMod,
  type ConfigPlugin,
} from 'expo/config-plugins';

/**
 * The Android hardening the bare template does not do for itself.
 *
 * Everything here is a property of the generated project that `app.config.ts`
 * has no field for. It is expressed as a plugin rather than as an edit to
 * `android/`, because that directory is regenerated from nothing on every
 * prebuild and a hand edit would survive exactly until the next one.
 *
 * `pnpm android:verify` asserts each of these against the manifest that comes
 * out the far end, so a plugin that silently stopped applying would fail the
 * gate rather than ship a weaker binary.
 */

/**
 * What the platform may copy off this device, which is nothing.
 *
 * Token material lives in the Android Keystore and never leaves the device it
 * was created on, so a backup could only ever carry the application's
 * non-secret state — but "only ever" is a claim about code that will change,
 * and the safer default costs a person one re-authentication after a device
 * transfer. `allowBackup="false"` closes cloud backup; these rules close the
 * device-to-device transfer that Android 12 added alongside it, which
 * `allowBackup` alone does not govern.
 */
const dataExtractionRules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/with-velora-android.ts. Do not edit. -->
<data-extraction-rules>
  <cloud-backup>
    <exclude domain="root" />
    <exclude domain="file" />
    <exclude domain="database" />
    <exclude domain="sharedpref" />
    <exclude domain="external" />
  </cloud-backup>
  <device-transfer>
    <exclude domain="root" />
    <exclude domain="file" />
    <exclude domain="database" />
    <exclude domain="sharedpref" />
    <exclude domain="external" />
  </device-transfer>
</data-extraction-rules>
`;

/** The same answer for Android 11 and earlier, which reads a different file. */
const backupRules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/with-velora-android.ts. Do not edit. -->
<full-backup-content>
  <exclude domain="root" path="." />
  <exclude domain="file" path="." />
  <exclude domain="database" path="." />
  <exclude domain="sharedpref" path="." />
  <exclude domain="external" path="." />
</full-backup-content>
`;

const withVeloraBackupRules: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    'android',
    (modified) => {
      const directory = join(
        modified.modRequest.platformProjectRoot,
        'app/src/main/res/xml',
      );
      mkdirSync(directory, { recursive: true });
      writeFileSync(
        join(directory, 'velora_data_extraction_rules.xml'),
        dataExtractionRules,
      );
      writeFileSync(join(directory, 'velora_backup_rules.xml'), backupRules);
      return modified;
    },
  ]);

const withVeloraApplicationAttributes: ConfigPlugin = (config) =>
  withAndroidManifest(config, (modified) => {
    const application = modified.modResults.manifest.application?.[0];
    if (application === undefined) {
      throw new Error('Generated AndroidManifest.xml has no <application>');
    }

    // Stated rather than inherited. Android 9 and later default to refusing
    // cleartext, but the default is a property of `targetSdkVersion`, and a
    // security posture that moves when a build number moves is not a posture.
    // The debug variant re-declares this as `true` at a higher merge priority
    // so Metro and the development client can still be reached over http.
    application.$['android:usesCleartextTraffic'] = 'false';
    application.$['android:allowBackup'] = 'false';
    application.$['android:dataExtractionRules'] =
      '@xml/velora_data_extraction_rules';
    application.$['android:fullBackupContent'] = '@xml/velora_backup_rules';

    // A launcher activity has to be exported; nothing else here does. The
    // template ships `MainActivity` exported for the LAUNCHER filter and every
    // component the dependencies contribute already declares itself
    // unexported, so this loop is an assertion rather than a change — and it
    // fails the prebuild rather than the gate if that ever stops being true.
    // Providers are covered by the gate rather than here: the manifest type
    // this API exposes has no field for them.
    for (const kind of ['activity', 'service', 'receiver'] as const) {
      for (const component of application[kind] ?? []) {
        const name = component.$['android:name'];
        if (name === '.MainActivity') continue;
        if (component.$['android:exported'] === 'true') {
          throw new Error(
            `Generated AndroidManifest.xml exports ${kind} ${name}. ` +
              'Only the launcher activity may be exported; block it or justify ' +
              'it in apps/mobile/plugins/with-velora-android.ts.',
          );
        }
      }
    }

    return modified;
  });

/**
 * Drops the development-only URL scheme from the shipped manifest.
 *
 * `expo prebuild` writes `exp+velora://` beside `velora://` so a project can be
 * opened from Expo Go. This application is not run from Expo Go — it has a
 * development client of its own, which uses the real scheme — so the extra
 * filter is a second publicly addressable entry point into the application that
 * nothing uses. Every deep link is validated and every destination is
 * re-authorized, so this is not the difference between safe and unsafe; it is
 * one fewer thing to have to say that about.
 */
const withVeloraSchemes: ConfigPlugin = (config) =>
  withAndroidManifest(config, (modified) => {
    const activity =
      modified.modResults.manifest.application?.[0]?.activity?.find(
        (candidate) => candidate.$['android:name'] === '.MainActivity',
      );
    for (const filter of activity?.['intent-filter'] ?? []) {
      const data = filter.data;
      if (data === undefined) continue;
      filter.data = data.filter(
        (entry) => entry.$['android:scheme'] !== 'exp+velora',
      );
    }
    return modified;
  });

/**
 * Release signing, and the refusal that makes it real.
 *
 * The bare template signs release builds with the debug keystore it ships —
 * a private key that is in every React Native project on the internet. That is
 * fine for a template and unacceptable for a product: an artifact signed with
 * it is not a release, it is a debug build wearing the word.
 *
 * So the debug signing config is not reachable from the release build type at
 * all. Release signing material is supplied at build time, never committed, and
 * read from Gradle properties or the environment. When it is absent the build
 * produces a deliberately **unsigned** artifact, which Google Play refuses to
 * accept — the failure lands where it belongs rather than one step later. A
 * release pipeline additionally passes `-Pvelora.android.requireSignedRelease=true`,
 * which turns the absence into a build failure instead of an unsigned file.
 *
 * See `docs/engineering/12-android-release-and-signing.md` for the four values
 * and how they are provisioned.
 */
const signingBlock = `
/**
 * Velora release signing. Written by apps/mobile/plugins/with-velora-android.ts.
 *
 * Every value is supplied at build time. Nothing here reads a committed secret,
 * and the release build type never falls back to the debug keystore.
 */
def veloraSigning(String name, String property) {
    def fromEnvironment = System.getenv(name)
    if (fromEnvironment != null && !fromEnvironment.trim().isEmpty()) {
        return fromEnvironment.trim()
    }
    def fromProperty = project.findProperty(property)
    if (fromProperty != null && !fromProperty.toString().trim().isEmpty()) {
        return fromProperty.toString().trim()
    }
    return null
}

ext.veloraKeystorePath = veloraSigning('VELORA_ANDROID_KEYSTORE_PATH', 'velora.android.keystorePath')
ext.veloraKeystorePassword = veloraSigning('VELORA_ANDROID_KEYSTORE_PASSWORD', 'velora.android.keystorePassword')
ext.veloraKeyAlias = veloraSigning('VELORA_ANDROID_KEY_ALIAS', 'velora.android.keyAlias')
ext.veloraKeyPassword = veloraSigning('VELORA_ANDROID_KEY_PASSWORD', 'velora.android.keyPassword')
ext.veloraReleaseSigningAvailable = ext.veloraKeystorePath != null &&
    ext.veloraKeystorePassword != null &&
    ext.veloraKeyAlias != null &&
    ext.veloraKeyPassword != null

if (!ext.veloraReleaseSigningAvailable) {
    def required = project.findProperty('velora.android.requireSignedRelease')
    if (required != null && required.toString() == 'true') {
        throw new GradleException(
            'Release signing material is missing. Set VELORA_ANDROID_KEYSTORE_PATH, ' +
            'VELORA_ANDROID_KEYSTORE_PASSWORD, VELORA_ANDROID_KEY_ALIAS and ' +
            'VELORA_ANDROID_KEY_PASSWORD, or drop velora.android.requireSignedRelease. ' +
            'See docs/engineering/12-android-release-and-signing.md.'
        )
    }
    logger.warn(
        'VELORA: no release signing material; release artifacts will be UNSIGNED and ' +
        'cannot be uploaded to Google Play. This is deliberate: the debug keystore is ' +
        'never used to sign a release.'
    )
}
`;

const withVeloraSigning: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (modified) => {
    if (modified.modResults.language !== 'groovy') {
      throw new Error('Expected a Groovy app/build.gradle');
    }
    let contents = modified.modResults.contents;

    const anchor = 'android {';
    if (!contents.includes(anchor)) {
      throw new Error('app/build.gradle has no android block');
    }
    contents = contents.replace(anchor, `${signingBlock}\n${anchor}`);

    // Add the release signing config beside the template's debug one.
    const debugSigningConfig = `    signingConfigs {
        debug {`;
    if (!contents.includes(debugSigningConfig)) {
      throw new Error(
        'app/build.gradle has no debug signingConfig to anchor to',
      );
    }
    contents = contents.replace(
      debugSigningConfig,
      `    signingConfigs {
        release {
            if (project.ext.veloraReleaseSigningAvailable) {
                storeFile file(project.ext.veloraKeystorePath)
                storePassword project.ext.veloraKeystorePassword
                keyAlias project.ext.veloraKeyAlias
                keyPassword project.ext.veloraKeyPassword
                // Both signature schemes Play App Signing expects of an upload.
                enableV1Signing true
                enableV2Signing true
            }
        }
        debug {`,
    );

    // The template's release build type points at the debug keystore. Replace
    // that line rather than adding beside it, so there is no path back to it.
    const templateRelease = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;
    if (!contents.includes(templateRelease)) {
      throw new Error(
        'app/build.gradle release build type no longer matches the template; ' +
          'the debug-keystore replacement in with-velora-android.ts needs revisiting',
      );
    }
    contents = contents.replace(
      templateRelease,
      `        release {
            // Never signingConfigs.debug. An artifact signed with the template's
            // shared debug key is not a release. Absent material means unsigned.
            signingConfig project.ext.veloraReleaseSigningAvailable ? signingConfigs.release : null`,
    );

    modified.modResults.contents = contents;
    return modified;
  });

const withVeloraAndroid: ConfigPlugin = (config) =>
  withVeloraSigning(
    withVeloraSchemes(
      withVeloraApplicationAttributes(withVeloraBackupRules(config)),
    ),
  );

export default withVeloraAndroid;
